languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false
title = "DSG Jam"
logo = "img/logo.png"
description = "My awesome website"
dateFormat = "2 January 2006"

[author]
name = "DSG"
image = "img/logo-circle.png"
links = [
  { email = "mailto:jam@dsg.li" },
  { github = "https://github.com/dsg-jam" },
]
